spring.application.name=celesma-api
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# JWT
app.jwt.expiration-ms=86400000

# OAuth2 Google
spring.security.oauth2.client.registration.google.scope=email,profile

# AI
ai.api.url=https://api.deepseek.com/v1/chat/completions

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false