storage.bucket-name=${STORAGE_BUCKET_NAME:bucket-name}
storage.access-key=${ACCESS_KEY:access-key}
storage.secret-key=${SECRET_KEY:secret-key}
storage.endpoint=${STORAGE_ENDPOINT:https://storage.yandexcloud.net}
storage.region=${STORAGE_REGION:ru-central1}